modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[13,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="economy"
type="required"
versionRange="[${economy_version},)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="openui_mc"
type="required"
versionRange="[${openui_version},)"
ordering="AFTER"
side="CLIENT"
