plugins { id 'com.gradleup.shadow' }

def commonProject = project(':common-1.21.1')
ext.minecraft_version = commonProject.minecraft_version
ext.architectury_api_version = commonProject.architectury_api_version
ext.neoforge_version = commonProject.neoforge_version
architectury { platformSetupLoomIde(); neoForge() }
configurations {
    common { canBeResolved = true; canBeConsumed = false }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
    shadowBundle { canBeResolved = true; canBeConsumed = false }
}
repositories { maven { url 'https://maven.neoforged.net/releases' } }
dependencies {
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"
    modImplementation "dev.architectury:architectury-neoforge:${project.architectury_api_version}"
    modImplementation "com.nstut:economy-neoforge-1.21.1:${rootProject.economy_version}"
    modImplementation "com.nstut:openui-mc-neoforge-1.21.1:${rootProject.openui_version}"
    implementation project(':common')
    common(project(path: ':common-1.21.1', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common-1.21.1', configuration: 'transformProductionNeoForge')
}
processResources {
    inputs.properties version: project.version, mod_id: rootProject.mod_id, mod_name: rootProject.mod_name, mod_description: rootProject.mod_description,
            mod_authors: rootProject.mod_authors, minecraft_version: project.minecraft_version, economy_version: rootProject.economy_version, openui_version: rootProject.openui_version
    filesMatching('META-INF/neoforge.mods.toml') { expand(inputs.properties) }
}
shadowJar { configurations = [project.configurations.shadowBundle]; archiveClassifier = 'dev-shadow' }
remapJar { inputFile.set shadowJar.archiveFile }
