modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="architectury"
mandatory=true
versionRange="[9,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="economy"
mandatory=true
versionRange="[${economy_version},)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="openui_mc"
mandatory=true
versionRange="[${openui_version},)"
ordering="AFTER"
side="CLIENT"
